- google/vit-base-patch16-224
- google/vit-large-patch16-224
- google/vit-large-patch16-384
- google/vit-large-patch32-384
- microsoft/beit-base-patch16-224-pt22k-ft22k
- microsoft/beit-large-patch16-224-pt22k-ft22k
- microsoft/beit-large-patch16-512
- microsoft/beit-large-patch16-384
- microsoft/beit-large-patch16-224
- microsoft/resnet-50
- microsoft/swinv2-large-patch4-window12to24-192to384-22kto1k-ft
- microsoft/swinv2-large-patch4-window12to16-192to256-22kto1k-ft
- microsoft/swinv2-large-patch4-window12-192-22k
- facebook/convnext-large-224
- facebook/convnextv2-large-22k-384
- facebook/convnextv2-large-22k-224