- google/vit-base-patch16-224
- google/vit-large-patch16-224
- google/vit-large-patch16-384
- google/vit-large-patch32-384
- microsoft/beit-base-patch16-224-pt22k-ft22k
- microsoft/beit-large-patch16-224-pt22k-ft22k
- microsoft/beit-large-patch16-512
- microsoft/beit-large-patch16-384
- microsoft/beit-large-patch16-224
- microsoft/resnet-50
- microsoft/resnet-101
- microsoft/swinv2-large-patch4-window12to24-192to384-22kto1k-ft
- microsoft/swinv2-large-patch4-window12to16-192to256-22kto1k-ft
- microsoft/swinv2-large-patch4-window12-192-22k
- facebook/convnext-large-224
- facebook/convnextv2-large-22k-384
- facebook/convnextv2-large-22k-224
- haywoodsloan/autotrain-ai-image-detect-20240716-0057
- haywoodsloan/autotrain-ai-image-detect-20240917-0133
- haywoodsloan/autotrain-ai-image-detect-20240919-0417
- haywoodsloan/autotrain-ai-image-detect-20240921-0910
- haywoodsloan/autotrain-ai-image-detect-20240927-0048
- haywoodsloan/autotrain-ai-image-detect-20240928-0332
- haywoodsloan/autotrain-ai-image-detect-20240929-0359
- haywoodsloan/autotrain-ai-image-detect-20240930-0105
- haywoodsloan/autotrain-ai-image-detect-20241001-0133
- haywoodsloan/autotrain-ai-image-detect-20241002-0308
- haywoodsloan/autotrain-ai-image-detect-20241003-0144
- haywoodsloan/autotrain-ai-image-detect-20241004-0020
- haywoodsloan/autotrain-ai-image-detect-20241005-0301
- haywoodsloan/autotrain-ai-image-detect-20241006-0346
- haywoodsloan/autotrain-ai-image-detect-20241007-0157
- haywoodsloan/autotrain-ai-image-detect-20241008-0319
- haywoodsloan/autotrain-ai-image-detect-20241009-0311
- haywoodsloan/autotrain-ai-image-detect-20241010-0202
- haywoodsloan/autotrain-ai-image-detect-20241012-0228
- haywoodsloan/autotrain-ai-image-detect-20241015-0237
- haywoodsloan/autotrain-ai-image-detect-20241016-0226
- haywoodsloan/autotrain-ai-image-detect-20241020-0142
- haywoodsloan/autotrain-ai-image-detect-20241022-0241
- haywoodsloan/autotrain-ai-image-detect-20241023-0025
- haywoodsloan/autotrain-ai-image-detect-20241029-0508
- haywoodsloan/autotrain-ai-image-detect-20241030-0302
- haywoodsloan/autotrain-ai-image-detect-20241031-0111