name: autotrain-advanced

services:
  app:
    build:
      dockerfile: app.Dockerfile
    environment:
      HF_TOKEN_FILE: /run/secrets/hf_key
    ports:
      - '7860:7860'
    secrets:
      - hf_key
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  cli:
    build:
      dockerfile: cli.Dockerfile
    environment:
      HF_TOKEN_FILE: /run/secrets/hf_key
      HF_USER_FILE: /hf_user
    volumes:
      - ./.compiled/config:/workspace/configs:ro
      - ./images/data:/workspace/haywoodsloan/ai-images/data:ro
    configs:
      - hf_user
    secrets:
      - hf_key
    stdin_open: true
    tty: true
    shm_size: 1gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

configs:
  hf_user:
    file: .huggingface_user

secrets:
  hf_key:
    file: .huggingface_key
