name: 'autotrain-advanced'

services:
  app:
    build: .
    secrets:
      - hf_key
    environment:
      HF_TOKEN_FILE: /run/secrets/hf_key
    ports:
      - '7860:7860'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

secrets:
  hf_key:
    file: .huggingface
